Transform: AWS::Serverless-2016-10-31
Resources:
  akimuraHelloHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../functions/hello-world
      Handler: hello.handler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Properties:
            Method: get
            Path: /hello
          Type: Api
    Metadata:
      aws:cdk:path: AkimuraCdkWorkshopStack/akimura-HelloHandler
  akimuraEndpoint:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
    Metadata:
      aws:cdk:path: AkimuraCdkWorkshopStack/akimura-Endpoint
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.8.0,@aws-cdk/assets=1.8.0,@aws-cdk/aws-cloudwatch=1.8.0,@aws-cdk/aws-ec2=1.8.0,@aws-cdk/aws-events=1.8.0,@aws-cdk/aws-iam=1.8.0,@aws-cdk/aws-kms=1.8.0,@aws-cdk/aws-lambda=1.8.0,@aws-cdk/aws-s3=1.8.0,@aws-cdk/aws-s3-assets=1.8.0,@aws-cdk/aws-sam=1.8.0,@aws-cdk/aws-sqs=1.8.0,@aws-cdk/aws-ssm=1.8.0,@aws-cdk/core=1.8.0,@aws-cdk/cx-api=1.8.0,@aws-cdk/region-info=1.8.0,jsii-runtime=node.js/v10.16.3

